amplience/dc-cli

src/commands/content-item/archive.spec.ts, src/commands/content-item/archive.ts, src/commands/content-item/unarchive.spec.ts, src/commands/content-item/unarchive.ts, src/commands/content-type-schema/archive.ts, src/commands/content-type-schema/unarchive.ts, src/commands/content-type/archive.ts, src/commands/content-type/unarchive.ts, src/common/archive/archive-options.ts, src/common/archive/unarchive-options.ts
This PR adds commands for **archive/unarchive** of content item.
You can archive by exact **content item ID**, **name** or by **repository ID**, **folder ID**, **content type URI**. Regex arguments are passed with forward slashes on either side, though when they contain spaces they still must be passed with quotes surrounding them like any other string argument (eg. `"/regex with space/"`). Not providing any argument will perform the action on **all content items** through all repositories in a specified hub, which can be useful.
The user is given a summary of all actions that will be taken in the command line, and must answer (y/n) for the action to be taken. If the user passes the `--force` argument, the answer `y` will be assumed.
These commands output a **"revert log"**, which is a …
=> feat(content-item): archive/unarchive content item commands

src/commands/content-item/export.ts, src/commands/content-item/import.ts, src/commands/content-type-schema/export.spec.ts, src/commands/content-type-schema/export.ts, src/commands/content-type/export.spec.ts, src/commands/content-type/export.ts, src/commands/content-type/import.ts, src/common/content-item/content-dependancy-tree.ts, src/interfaces/export-builder-options.interface.ts, src/services/export.service.ts, src/services/import.service.ts
This PR changes the functionality of existing `content-type` and `content-type-schema` export commands:
- The `export` command now generates the destination folder if it did not already exist.
- This better matches the behaviour of the content-item export commands.
- The tests have been updated to reflect this.
- When listing content type schema for export, explicitly list only those with "ACTIVE" status, not archived.
- If a user wants to include archived content type schema, they can pass in the `--archived` option, which will restore the old behaviour
- `content-type` commands do not have this treatment, as they only fetch active content-types on list. This mismatch is a problem with the API, where the behaviour where no status filter is given seems to be different between schemas and …
=> feat(content-type-schema): make exporting archived schema optional, automatically create destination

src/commands/content-item/__mocks__/copy.ts, src/commands/content-item/__mocks__/import.ts, src/commands/content-item/copy.spec.ts, src/commands/content-item/copy.ts, src/commands/content-item/export.spec.ts, src/commands/content-item/export.ts, src/commands/content-item/import.spec.ts, src/commands/content-item/import.ts, src/commands/content-item/move.spec.ts, src/commands/content-item/move.ts, src/common/content-item/copy-config.spec.ts, src/common/content-item/copy-config.ts, src/common/file-log.ts, src/interfaces/copy-item-builder-options.interface.ts, src/interfaces/import-item-builder-options.interface.ts, temp/move/failLog.txt
This PR adds `copy` and `move` commands to the `content-item` set of commands. These are essentially a nice wrapper for `import` and `export`, which does the work of creating and deleting a temp folder for you, and can work with one command.
By default, the source and destination hubs for these commands are both defined by your dc-cli config, meaning a copy/move within the same hub. If you want the destination to be different from the source, you'll need to specify the destination's config in the commands, eg: `--dstHub <hubID> --dstClientId <clientId> --dstSecret <secret>`
Copies, moves and imports are also now revertable. Pass in the parameter `--revertLog <log path>` with your destination hub info and log generated from copy/move, and it will archive or revert any content items created …
=> feat(content-item): add copy and move commands

package-lock.json, src/commands/content-item/archive.ts, src/commands/content-item/export.ts, src/commands/content-item/import-revert.spec.ts, src/commands/content-item/import.spec.ts, src/commands/content-item/import.ts, src/commands/content-item/unarchive.ts, src/commands/content-type-schema/archive.ts, src/commands/content-type-schema/unarchive.ts, src/commands/content-type/archive.ts, src/commands/content-type/unarchive.ts, src/common/archive/archive-log.spec.ts, src/common/archive/archive-log.ts, src/common/file-log.spec.ts
This PR changes the reporting of errors and warnings into the log to be more consistent, and machine readable.
When an error occurs, there is now an `ERROR` or `WARNING` action inserted into the logs.
When any error or warning occurs, the overall error level of the log is increased to match the error. This is printed at the end of the file as `SUCCESS` if there are no warnings or errors, `FAILURE` if there are errors, or the highest error level otherwise.
The errors logs themselves have been made more consistent - logs with `Error` instances will now print them on the next line all of the time, rather than inconsistently as part of the string template.
This shouldn't be a breaking change. The final return code is on the last line of the log, which was previously empty. (the log ended with …
=> feat(log): log errors in a more consistent fashion

src/commands/configure.spec.ts, src/commands/configure.ts, src/commands/content-item/__mocks__/dependant-content-helper.ts, src/commands/content-item/__snapshots__/tree.spec.ts.snap, src/commands/content-item/import.ts, src/commands/content-item/tree.spec.ts, src/commands/content-item/tree.ts, src/common/content-item/content-dependancy-tree.ts
(Previous feedback on my fork, at https://github.com/rs-amp/dc-cli/pull/1 )
This command allows you to print a dependency tree for any folder of content items on your system. The input directory should contain content items in the same format that the `export` command generates. It does not require repo/folder layouts, just that all dependent content is contained within the parent directory.
`dc-cli content-item tree <dir>`
This uses the same dependency tree class as the import task, which uses it to import the deepest content items first so that references can be properly resolved. Here, the "levels" of content items are maintained, and the highest level (most layers of dependencies) is printed first, followed by the lower levels that have not been printed yet.
Each item shows the items …
=> feat(content-item): add tree command, improved circular dependency import

src/commands/content-type-schema/export.ts, src/commands/content-type/__snapshots__/export.spec.ts.snap, src/commands/content-type/__snapshots__/import.spec.ts.snap, src/commands/content-type/export.spec.ts, src/commands/content-type/export.ts, src/commands/content-type/import.spec.ts, src/commands/content-type/import.ts, src/services/export.service.ts, src/services/import.service.ts
This PR contains:
- fix of export content type schemas in case when schema urls contain special characters as **:**, **!**, **?** etc. 
Special characters (especially **:** ) caused an issue on creating files on export schemas command on windows. 
- added list or repositories to a content type export command to use this list on import command to assign content types to repositories
=> fix(export): content type schemas and content types special characters

src/common/json-resolver/json-resolver.spec.ts, src/common/json-resolver/json-resolver.ts
The JSON files as part of exports have their paths in unix format, but the user can provide windows style paths when running the `update` and `create` `content-type-schema` commands. This PR makes sure that both are properly handled when calculating relative paths.
Fixes `content-type-schema` import on Windows.
=> fix: json-exporter can now handle both windows and unix paths, regardless of host os

src/commands/content-type-schema/import.ts
Fixes an issue where schema import would report 'UP-TO-DATE' when importing schemas, but the schema on the server was archived. This makes it behave more in line with what is expected in the hub clean / import process.
=> fix(content-type-schema): always treat archived schemas as out of date

.github/workflows/nodejs.yml, jest.config.js, jest.global.js, package.json, src/cli.spec.ts, src/commands/content-item/archive.spec.ts, src/commands/content-item/copy.spec.ts, src/commands/content-item/export.spec.ts, src/commands/content-item/import-revert.spec.ts, src/commands/content-item/import.spec.ts, src/commands/content-item/move.spec.ts, src/commands/content-item/tree.spec.ts, src/commands/content-item/unarchive.spec.ts, src/commands/content-type-schema/archive.spec.ts, src/commands/content-type-schema/unarchive.spec.ts, src/commands/content-type/archive.spec.ts, src/commands/content-type/unarchive.spec.ts, src/commands/event/archive.spec.ts, src/commands/hub/clean.spec.ts, src/commands/hub/clone.spec.ts, src/commands/hub/steps/content-clean-step.spec.ts, src/commands/hub/steps/content-clone-step.spec.ts, src/commands/hub/steps/schema-clean-step.spec.ts, src/commands/hub/steps/schema-clone-step.spec.ts, src/commands/hub/steps/settings-clone-step.spec.ts, src/commands/hub/steps/type-clean-step.spec.ts, src/commands/hub/steps/type-clone-step.spec.ts, src/common/archive/archive-log.spec.ts, src/common/file-log.spec.ts
Updated all tests that write temp files to use the jest WORKER_ID, to allow the tests to run in parallel.
Fixes another issue with spying on `ensureDirectoryExists`, where it wasn't reset after the spy.
=> fix: unit test logging

src/cli.ts, src/commands/configure.spec.ts, src/commands/configure.ts
This will print a clean error when the config file cannot be parsed. The error is ignored when using the `configure` command, as the goal is to replace the configuration file anyways.
=> feat(config): print helpful error if config file is invalid json

package-lock.json, src/commands/content-item/archive.spec.ts, src/commands/content-type-schema/archive.spec.ts, src/commands/content-type/archive.spec.ts, src/commands/event/archive.spec.ts, src/common/file-log.spec.ts, src/common/file-log.ts, src/common/log-helpers.spec.ts, src/common/log-helpers.ts
This PR adds the CLI tool version to the titles of log files generated by commands. Some tests have been updated to set a dummy version `test-ver` so that their snapshots still work.
=> feat(file-log): add version to file-log title

src/commands/content-item/copy.spec.ts, src/commands/content-item/copy.ts, src/commands/content-item/import.spec.ts, src/commands/content-item/import.ts, src/commands/content-item/move.ts, src/commands/hub/clone.spec.ts, src/commands/hub/clone.ts, src/common/dc-management-sdk-js/mock-content.ts
This catches two cases which forced people to use the `--republish` command, unnecessarily publishing all assets instead of just the ones they're interested in:
- Running `--publish` after importing without it. Before, it would only publish content that was updated (uploading the content resulted in version increase), so it would not publish the content that wasn't published the first time. This meant that people that took this workflow had to use `--republish` to avoid issues.
- Running `--publish` after republishing content in the source will also republish in the destination, even if it hasn't changed. This can also be triggered manually by fudging the publish date in the file.
This does cause a small functional change in that the `lastPublishedDate` is now the source of truth for a …
=> feat(content-item): make --publish flag publish on update when source publish date is more recent

HOW_TO_USE.md, src/commands/content-item/archive.spec.ts, src/commands/content-item/archive.ts, src/commands/content-item/copy.spec.ts, src/commands/content-item/copy.ts, src/commands/content-item/export.spec.ts, src/commands/content-item/export.ts, src/commands/content-item/move.spec.ts, src/commands/content-item/move.ts, src/commands/content-item/unarchive.spec.ts, src/commands/content-item/unarchive.ts, src/commands/event/archive.ts, src/common/archive/archive-event-options.ts, src/common/archive/archive-options.ts, src/common/archive/unarchive-options.ts, src/common/filter/facet.spec.ts, src/common/filter/facet.ts, src/interfaces/copy-item-builder-options.interface.ts, src/interfaces/export-item-builder-options.interface.ts
This PR replaces the existing `--name` and `--schemaId` arguments with an all encompassing `--facet` argument, which adds filtering by locale and date modified.
These filters can be applied to any array of content items, and can currently be used on `content-item` `archive` `unarchive` `copy` `move` and `export`. As of right now, the facets are applied in software after fetching _all_ content items (within the requested hub/repo/folder), though it is possible in the future to extend this to request content with the facets to save time in future. Note that the regex faceting mode will likely not see this treatment.
A full explanation of the `--facet` argument has been added to the `HOW_TO_USE.md` file. I'll dupe it below for ease of access:
The content item export, copy, move, archive and …
=> feat: facet argument for content item commands 

src/commands/search-index/__snapshots__/import.spec.ts.snap, src/commands/search-index/import.spec.ts, src/commands/search-index/import.ts
Replica names were not being rewritten when importing into a new hub. This PR should fix that issue.
=> fix(search-index): fix replica name rewriting

src/commands/content-type/__snapshots__/import.spec.ts.snap, src/commands/content-type/import.spec.ts, src/commands/content-type/import.ts, src/commands/extension/__snapshots__/import.spec.ts.snap, src/commands/extension/import.spec.ts, src/commands/extension/import.ts, src/commands/search-index/__snapshots__/import.spec.ts.snap, src/commands/search-index/export.spec.ts, src/commands/search-index/export.ts, src/commands/search-index/import.spec.ts, src/commands/search-index/import.ts
This PR fixes an issue where empty import on certain commands would cause the command to error out, which would interrupt the clone command despite the import technically succeeding (as it didn't have to do anything).
This also fixes an issue where search index list would throw an exception if it is disabled on the target account. In this case, the export is now simply skipped.
=> fix: allow empty import without error, fix search index export on accounts where it is disabled

README.md
Fixes some argument duplicates in the config examples in the readme.
Changes
`dc-cli configure --clientId foo --clientId bar ...`
to
`dc-cli configure --clientId foo --clientSecret bar ...`
=> docs(readme): fix duplicate arguments in config examples

package-lock.json, package.json
Fixes two issues with the `dc-management-sdk-js` that were causing events with more than 20 slots to make the same request infinitely, as when requesting pages after the 0th it would just get page 0 back. There was no way to get anything after the first 20 slots.
=> fix(event): fix event slots list pagination

docs/CONTENT-ITEM.md, docs/HUB.md, src/commands/content-item/copy.spec.ts, src/commands/content-item/copy.ts, src/commands/content-item/import.spec.ts, src/commands/content-item/import.ts, src/commands/content-item/move.spec.ts, src/commands/content-item/move.ts, src/commands/hub/clone.ts, src/common/import/publish-queue.spec.ts, src/common/import/publish-queue.ts, src/interfaces/clone-hub-builder-options.ts, src/interfaces/copy-item-builder-options.interface.ts, src/interfaces/import-item-builder-options.interface.ts
This is an alternative implementation to #145 which extends the existing publishing queue to support concurrent publishes.
Benefits:
- Publish() method actually starts the publish, dispatching is limited by both the rate limit and the concurrency limit.
- Not too much change from the existing publish queue.
Downsides:
- Custom implementation of batching rather than a standard one, though this was technically already in place originally.
=> feat: concurrent publish queue with --batchPublish option

src/commands/content-item/__mocks__/dependant-content-helper.ts, src/common/content-item/content-dependancy-tree.spec.ts, src/common/content-item/content-dependancy-tree.ts
The code to skip publishing child items assumed that both content links and content references would be followed and published when their parent is, but that is only the case for links. This fixes the issue, and adds a test to verify that traversal only follows links when asked to.
=> fix(content-item): only assume links will be published, not references

src/commands/content-item/archive.spec.ts, src/commands/content-item/archive.ts
This fixes an issue where the content-item archive command would error if the facet used could be accelerated.
The problem is that we need the content body to determine if the delivery-key is present, which is used to determine if it is to be removed on archive. This is not available when content is retrieved from the facet endpoint, so it was erroring instead.
The downside is that this might make content-item archive a little slower than it would be without the delivery key check, but this ensures that it works the same with and without the facet.
=> fix(content-item): enrich items when faceting for archive

src/commands/hub/clean.ts, src/commands/hub/clone.ts
Fix a regression from #149 that would stop hub clean/clone commands from working.
=> fix(hub): fix hub commands not being passed credentials

src/commands/event/archive.spec.ts, src/commands/event/archive.ts
To archive events, all contained editions must be archived. However, if an edition has never been published (its scheduled time never arrived) then it cannot be archived. The correct process here is unscheduling the edition, then _deleting_ it, though only the first part was done which would result in an error. This PR fixes the issue.
=> fix(events): correctly archive events with unscheduled editions

docs/SETTINGS.md, src/commands/settings/import.spec.ts, src/commands/settings/import.ts, src/interfaces/import-settings-builder-options.interface.ts
Before, existing preview settings would not be touched when importing new ones. This PR allows new preview settings to overwrite existing ones, which is useful for overwriting the URL. Settings import still cannot delete preview settings.
=> feat(settings): overwrite existing preview settings rather than ignoring updates
